---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: kubecost
spec:
  chart:
    spec:
      chart: cost-analyzer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubecost-charts
        namespace: flux-system
      version: 1.92.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: kubecost
  values:
    global:
      thanos:
        enabled: false
    kubecostToken: ZWxhbWFyYXNAYW1hem9uLmNvbQ==xm343yadf98
    networkCosts:
      enabled: true

