apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: kubecost
spec:
  interval: 1m
  chart:
    spec:
      chart: cost-analyzer
      version: "1.92.0"
      sourceRef:
        kind: HelmRepository
        name: kubecost-charts
        namespace: flux-system
      interval: 1m
  values:
    networkCosts:
      enabled: true
    kubecostProductConfigs:
      clusterName: elas-mgmt
      serviceKeySecretName: gcp-secret
    global:
      thanos:
        enabled: false
