---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: hello-eksa
  namespace: default
spec:
  hostname: "hello.eksa-demo.cluster-a"
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hello-backend
  namespace: default
spec:
  prefix: /
  service: hello-eks-a
  hostname: "hello.eksa-demo.cluster-a"
---
